name: Build import graphs
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pydeps
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Generate and commit graphs
        run: |
          [ -f app/__init__.py ] || touch app/__init__.py
          [ -f db/__init__.py ]  || touch db/__init__.py
          pydeps app -o imports_app.svg || true
          pydeps db  -o imports_db.svg  || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add imports_app.svg imports_db.svg || true
          git commit -m "CI: update import graphs" || exit 0
          git push
