      - name: Commit diagrams
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add imports_app.svg imports_db.svg
          git commit -m "CI: update import graphs" || echo "No changes"

          # <-- Nouveau : se remettre à jour avant de pousser
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }} || true

          git push origin HEAD:${{ github.ref_name }}
